# Generated by Django 3.1.1 on 2020-10-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0003_auto_20201014_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('date_added', models.DateField()),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('library_book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.librarybook')),
            ],
        ),
    ]
