# Generated by Django 3.1.1 on 2020-10-16 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201016_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 10, 16, 12, 38, 41, 468713, tzinfo=utc)),
        ),
    ]
