# Generated by Django 3.1.1 on 2020-10-16 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201016_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
