# Generated by Django 3.1.1 on 2020-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201016_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
