# Generated by Django 3.1.1 on 2020-10-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_Ordered',
            new_name='is_ordered',
        ),
    ]
