# Generated by Django 3.1.1 on 2020-10-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201016_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='library_book',
            field=models.ManyToManyField(to='cart.OrderBook'),
        ),
    ]
