# Generated by Django 3.1.1 on 2020-10-17 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_auto_20201017_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='library_book',
            field=models.ManyToManyField(blank=True, to='cart.OrderBook'),
        ),
    ]
