# Generated by Django 3.1.1 on 2020-10-19 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_loanedbooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanedBooks',
            new_name='LoanedBook',
        ),
    ]
