# Generated by Django 3.1.1 on 2020-10-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '__first__'),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('library', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraries.library')),
            ],
        ),
    ]
