# Generated by Django 3.1.1 on 2020-10-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '__first__'),
        ('libraries', '0002_librarybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='library',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.library'),
        ),
    ]
