# Generated by Django 3.1.1 on 2020-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_auto_20201014_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_library.jpg', upload_to='library_pics'),
        ),
    ]
